import re

quotes = [
    "Over 1.8 billion people use Gmail worldwide.",
    "Gmail blocks 99.9% of spam, phishing, and malware.",
    "Your OTPs are sensitive and should never be shared.",
    "Gmail processes over 100 billion emails every day.",
    "100% Private, everything runs locally on your device.",
    "Enable 2FA on your Google Account for maximum security.",
    "OTP Syncer never sends your emails to external servers.",
    "Automated systems send millions of OTPs every single minute.",
    "Security is a journey, not a destination.",
    "Keep your device updated to ensure the best security.",
    "OTP Syncer uses the official Google APIs for safety.",
    "Google's advanced AI protects your inbox from threats.",
    "Your data stays on your device, always.",
    "We respect your privacy by doing all processing locally.",
    "Fast, secure, and reliable OTP synchronization.",
    "Never miss a login code again.",
    "Your workflow, uninterrupted.",
    "Seamless connection between your phone and PC.",
    "AES-256 encryption protects your data in transit.",
    "Syncing securely via Firebase Realtime Database.",
    "No more typing 6-digit codes manually.",
    "Efficiency meets security.",
    "Designed for professionals who value their time.",
    "Copying your OTPs so you don't have to.",
    "Automatically detecting codes in milliseconds.",
    "Built with privacy-first architecture.",
    "Open source technologies power the modern web.",
    "Simplifying your 2FA experience.",
    "The most secure way to handle your verification codes.",
    "Zero-knowledge architecture keeps your data safe.",
    "Protecting your digital identity, one OTP at a time.",
    "Seamlessly bridging your mobile and desktop devices.",
    "Empowering you with fast and secure logins.",
    "Security is not just a feature, it's our foundation.",
    "Experience the magic of instant OTP sync.",
    "Say goodbye to manually retyping codes.",
    "Your digital life, secured and simplified.",
    "We believe in technology that works for you.",
    "Trust is built through transparency and security.",
    "Empowering productivity with secure automation.",
    "The modern way to handle two-factor authentication.",
    "Your security is our top priority.",
    "Fast, frictionless, and secure by design.",
    "Protecting your accounts with advanced encryption.",
    "Seamless OTP delivery, right to your clipboard.",
    "Focus on your work, we'll handle the OTPs.",
    "Security that doesn't slow you down.",
    "The smartest way to sync your verification codes.",
    "Built for speed, engineered for security.",
    "Your seamless login experience starts here.",
    "Empowering secure connections across your devices.",
    "The ultimate tool for managing your OTPs.",
    "Security and convenience, perfectly balanced.",
    "Your digital security, simplified.",
    "Experience the future of two-factor authentication.",
    "Fast, reliable, and always secure.",
    "Your trusted companion for secure logins.",
    "Seamlessly syncing your OTPs in real-time.",
    "The intelligent way to manage your verification codes.",
    "Empowering your digital life with secure automation.",
    "Security you can trust, convenience you will love.",
    "Your fast track to secure logins.",
    "The elegant solution for two-factor authentication.",
    "Seamlessly integrating security into your workflow.",
    "Empowering you with fast, secure, and reliable OTP sync.",
    "Your digital identity, protected and simplified.",
    "The modern standard for secure OTP management.",
    "Fast, frictionless, and incredibly secure.",
    "Your seamless, secure login experience.",
    "Empowering your digital journey with secure automation.",
    "The intelligent, secure way to handle OTPs.",
    "Security that works with you, not against you.",
    "Your fast, reliable, and secure OTP companion.",
    "Seamlessly bridging the gap between security and convenience.",
    "Empowering you with the ultimate OTP sync experience.",
    "Your digital life, secured with advanced encryption.",
    "The smartest, most secure way to manage your codes.",
    "Fast, reliable, and designed with your privacy in mind.",
    "Your trusted solution for seamless secure logins.",
    "Seamlessly syncing your OTPs with zero-knowledge architecture.",
    "Empowering your productivity with secure, instant OTP delivery.",
    "The modern, secure approach to two-factor authentication.",
    "Security that empowers your digital lifestyle.",
    "Your fast, secure, and reliable login companion.",
    "Seamlessly integrating advanced security into your daily routine.",
    "Empowering you with the tools for a secure digital life.",
    "Your digital identity, safeguarded by cutting-edge encryption.",
    "The intelligent, privacy-first way to manage your OTPs.",
    "Fast, reliable, and uncompromisingly secure.",
    "Your trusted partner for seamless, secure verification.",
    "Seamlessly syncing your codes with unparalleled security.",
    "Empowering your digital experience with secure, instant automation.",
    "The modern, elegant solution for secure logins.",
    "Security that enhances your workflow.",
    "Your fast, secure, and intuitive OTP sync tool.",
    "Seamlessly bridging your devices with robust security.",
    "Empowering you to take control of your digital security.",
    "Your digital life, protected by our privacy-first approach.",
    "The smartest, most reliable way to handle your verification needs.",
    "Fast, secure, and designed to simplify your life."
]

with open('f:/Piyush Work/Software Making/Gmail Otp Syncer/android/app/src/main/java/com/mailsync/app/ui/AppNavigation.kt', 'r', encoding='utf-8') as f:
    content = f.read()

quotes_str = ',\n        '.join(['\"' + q + '\"' for q in quotes])
replacement = 'val quotes = listOf(\n        ' + quotes_str + '\n    )'

new_content = re.sub(r'val quotes = listOf\([^)]+\)', replacement, content, flags=re.MULTILINE|re.DOTALL)

with open('f:/Piyush Work/Software Making/Gmail Otp Syncer/android/app/src/main/java/com/mailsync/app/ui/AppNavigation.kt', 'w', encoding='utf-8') as f:
    f.write(new_content)
